### ISSUE TITLE
Hello, I have 1 problem when I import PyTangoArchiving, Can you help me

### ISSUE THREAD

**Issue by dvjdjvu** [tango-controls/PyTangoArchiving#19]
Traceback (most recent call last):
  File "./1.py", line 4, in <module>
    import PyTangoArchiving
  File "/usr/local/lib/python2.7/dist-packages/PyTangoArchiving-8.15.0-py2.7.egg/PyTangoArchiving/__init__.py", line 73, in <module>
    from schemas import Schemas
  File "/usr/local/lib/python2.7/dist-packages/PyTangoArchiving-8.15.0-py2.7.egg/PyTangoArchiving/schemas.py", line 76, in <module>
    class Schemas(object):
  File "/usr/local/lib/python2.7/dist-packages/PyTangoArchiving-8.15.0-py2.7.egg/PyTangoArchiving/schemas.py", line 129, in Schemas
    @fn.Cached(expire=60.)
AttributeError: 'module' object has no attribute 'Cached'
tango-cs@tangobox:~/imatrex/hdbpp$

**Comment by dvjdjvu** [comment]
I have resolved it.

**Comment by sergirubio** [comment]
Hi @dvjdjvu , thanks for closing the topic. But, may I know the nature of the error? There' s something wrong with the package in pip?

This package is actually valid only for the MySQL version of hdbpp, we plan to release soon the Timescale/Postgresql version.

**Comment by dvjdjvu** [comment]
My default pip was not pip2, It was pip3.7. I have installed PyTangoArchiving from source, but fantango installed from pip(using pip3.7)
