### ISSUE TITLE
PyTangoArchiving in anaconda environement

### ISSUE THREAD

**Issue by jcmarrucho** [tango-controls/PyTangoArchiving#21]
Hi,

I would like to use PyTangoArchiving in a anaconda environnement with python 3, installed on windows 10.

In my  conda env, i installed from pipy:
`pip install PyTangoArchiving`

Following is the result of `pip/conda list`:

`ca-certificates           2021.10.26           haa95532_2
certifi                   2021.10.8        py37haa95532_0
fandango                  14.8.0                   pypi_0    pypi
openssl                   1.1.1l               h2bbff1b_0
pip                       21.2.4           py37haa95532_0
pytango                   9.3.3                    pypi_0    pypi
pytangoarchiving          8.12.2                   pypi_0    pypi
python                    3.7.11               h6244533_0
setuptools                58.0.4           py37haa95532_0
six                       1.16.0                   pypi_0    pypi
sqlite                    3.36.0               h2bbff1b_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.37.0             pyhd3eb1b0_1
wincertstore              0.2              py37haa95532_2
`

When i try to import in python 3, i have the following error:
`>>> import PyTangoArchiving
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\marrucho\Anaconda3\envs\test_snap_1\lib\site-packages\PyTangoArchiving\__init__.py", line 62, in <module>
    import fandango as fn
  File "C:\Users\marrucho\Anaconda3\envs\test_snap_1\lib\site-packages\fandango\__init__.py", line 59
    except Exception,e:
                    ^
SyntaxError: invalid syntax`

Is this a problem from fandango ? python 3 ?

Thanks.

**Comment by jcmarrucho** [comment]
Hi,

For information, I note that the latest versions of fandango and pytangoarchiving are not up to date on pypi:

    fandango:     14.16.0 (https://gitlab.com/tango-controls/fandango)     14.8.0 (pip install)

    pytangoarchiving:     8.21.1 (https://github.com/tango-controls/PyTangoArchiving)     8.12.2 (pip install)

**edit:** To clarify and about PyTangoArchiving only:
the latest version on github (https://github.com/tango-controls/PyTangoArchiving) is 8.21.1 Released on 12 may 2020 
while the one on pypi (https://pypi.org/project/PyTangoArchiving/) is 8.12.2 Released on April 29, 2020 
Do these versions work with python 3?

Also, I tried to install the latest version of fandango (https://pypi.org/project/fandango/), with following error:(

**pip install fandango==14.17.1**
`ERROR: Could not find a version that satisfies the requirement fandango==14.17.1 (from versions: 11.7.2, 11.15, 12.0.1, 12.2.0, 12.2.2, 12.2.3, 12.6.1, 13.2.5, 13.7.0, 13.9.0, 14.3.0, 14.6.0, 14.6.1, 14.7.0, 14.7.1, 14.8.0)
ERROR: No matching distribution found for fandango==14.17.1`

Are fandango and pytangoarchiving compatible with python 3?

Thanks.

**Comment by sergirubio** [comment]
Hi,

If possible, login to gitlab, as the project has been moved there, and comment with your own username:

https://gitlab.com/tango-controls/hdbpp/libhdbpp-pytangoarchiving/-/issues/21

Keep in mind that PyTangoArchiving is currently python 2 only (at the moment), fandango is ongoing migration and pytangoarchiving has a new api available in python3 (just for extraction):

https://gitlab.com/tango-controls/hdbpp/libhdbpp-python

Sergi
